sudo: true

language: node_js

node_js:
  - "4"
  - "6"

os:
  - linux
  # - osx
  # - windows

script: npm run test

env:
  - "ES_VERSION=2.3.4"
  - "ES_VERSION=5.0.0-alpha4"

before_install:
  ## ES has different download locations for each version, so we'll download them both and then just use the one we want
  - curl -O https://download.elastic.co/elasticsearch/release/org/elasticsearch/distribution/deb/elasticsearch/$ES_VERSION/elasticsearch-$ES_VERSION.deb
  ## Now, use the ENV to choose the version
  - sudo dpkg -i --force-confnew elasticsearch-$ES_VERSION.deb
  - 'echo -e "index.number_of_shards: 1\nindex.number_of_replicas: 0" | sudo tee -a /etc/elasticsearch/elasticsearch.yml'
  - sudo service elasticsearch restart
  # ES needs some time to start
  - sleep 15
