sudo: true

language: node_js

node_js:
  - "4"
  - "6"

os:
  - linux
  # - osx
  # - windows

script: npm run test

env:
  - "ES_DOWNLOAD_URL=https://download.elastic.co/elasticsearch/release/org/elasticsearch/distribution/deb/elasticsearch/2.3.4/elasticsearch-2.3.4.deb"
  - "ES_DOWNLOAD_URL=https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-5.0.2.deb"

before_install:
  ## ES has different download locations for each version, so we'll download them both and then just use the one we want
  - curl $ES_DOWNLOAD_URL > elasticsearch_package.deb
  ## Now, use the ENV to choose the version
  - sudo dpkg -i --force-confnew elasticsearch_package.deb
  - 'echo -e "index.number_of_shards: 1\nindex.number_of_replicas: 0" | sudo tee -a /etc/elasticsearch/elasticsearch.yml'
  - sudo service elasticsearch restart
  # ES needs some time to start
  - sleep 15
  - curl http://localhost:9200
